project:
  type: website

website:
  title: "Website 2"
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: About
      href: about.qmd
    - text: Sources
      menu:
        - text: Source 1
          href: source-1.qmd
        - text: Source 2
          href: source-2.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



